## NUMPY ASSIGNMENT

In [ ]:
1:ans:- A list is a built-in data type in Python that is used to store a collection of values.
        It is a dynamic data type, which means that the size of the list can change during runtime. 
        A list can contain elements of different data types.
        
        An array is a data structure that is used to store a fixed-size sequential collection of elements 
        of the same data type.Unlike a list, an array has a fixed size that cannot be changed during runtime.

In [1]:
import numpy as np

In [2]:
list_ = ['1','2','3','4','5']

In [3]:
array_list = np.array(object = list_)

In [4]:
print(type(list_))

<class 'list'>


In [5]:
print(type(array_list))

<class 'numpy.ndarray'>


In [ ]:
2:ans:- the codes are :-

In [6]:
list_ = ['1','2','3','4','5']

In [7]:
array_list = np.array(object = list_)

In [8]:
for elem in list_:
    print(type(elem))  

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


In [9]:
for elem in array_list:
    print(type(elem))

<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


In [ ]:
3:ans:- the code is:-

In [10]:
array_list = np.array(object = list_ , dtype = int)

In [12]:
array_list

array([1, 2, 3, 4, 5])

In [13]:
for elem in array_list:
    print(type(elem))

<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


In [ ]:
4.ans:- the codes are:-

In [14]:
import numpy as np

In [15]:
num_list = [[ 1,2,3] , [4,5,6]]

In [16]:
num_array = np.array(object = num_list)

In [17]:
shape = num_array.shape
print("Shape of array:", shape)

Shape of array: (2, 3)


In [19]:
size = num_array.size
print("Size of array:", size)

Size of array: 6


In [ ]:
5:ans:- codes are:-

In [20]:
import numpy as np

In [21]:
zeros_array = np.zeros((3, 3))

In [22]:
print(zeros_array)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
6:ans:- codes are :-

In [23]:
import numpy as np

In [24]:
identity_matrix = np.identity(5)
print(identity_matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
